Update all plugins, correct javadocs, cleanup Travis Build Setup, and support openjdk13 builds (#17)
* [ci] Cleanup travis setup

- Removed sudo 'false' as it is obsolete and no longer considered
- Removed distro 'trusty' as it is legacy setup and unnecessary
- Removed commented out openjdk6 as it is not supported anyway
- Removed openjdk7 as it is no longer supported
- Replaced 'oracle' with 'open' on all jdks as licensing restrictions means it's no longer supported on newer builds.
- Removed oraclejdk9 as it is no longer supported
- Added openjdk13

* [pom] Update all the plugins

* [ci] Remove javadoc skip as unnecessary

* [ci] Remove gpg skip as those only run under release plugin per profile

* [pom] Remove 'source' attribute from javadoc as not necessary

The code base doesn't target 8 itself so setting this is not a good choice at the moment.

* [pom] Add profile to bump compiler for jdk higher than 11

* [ci] Remove all special overrides on travis as unnecessary now

* [javadoc] Correct header usage h2 is after h1 not h3

If further adjustment is needed, add font usage as necessary.  This is a hard break on jdk 13 as

```[ERROR] Exit code: 1 - /home/travis/build/hazendaz/json-sanitizer/src/main/java/com/google/json/JsonSanitizer.java:31: error: heading used out of sequence: <H3>, compared to implicit preceding heading: <H1>```